services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=rss-scraper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: .
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"
