// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"time"

	"github.com/google/uuid"
)

type ApiKeyAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

// Ref: #/components/schemas/FeedResponse
type FeedResponse struct {
	Feeds []FeedResponseItem `json:"feeds"`
}

// GetFeeds returns the value of Feeds.
func (s *FeedResponse) GetFeeds() []FeedResponseItem {
	return s.Feeds
}

// SetFeeds sets the value of Feeds.
func (s *FeedResponse) SetFeeds(val []FeedResponseItem) {
	s.Feeds = val
}

func (*FeedResponse) feedsFollowGetRes() {}
func (*FeedResponse) feedsGetRes()       {}

// Ref: #/components/schemas/FeedResponseItem
type FeedResponseItem struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	URL       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
}

// GetID returns the value of ID.
func (s *FeedResponseItem) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *FeedResponseItem) GetName() string {
	return s.Name
}

// GetURL returns the value of URL.
func (s *FeedResponseItem) GetURL() string {
	return s.URL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *FeedResponseItem) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *FeedResponseItem) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetUserID returns the value of UserID.
func (s *FeedResponseItem) GetUserID() uuid.UUID {
	return s.UserID
}

// SetID sets the value of ID.
func (s *FeedResponseItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *FeedResponseItem) SetName(val string) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *FeedResponseItem) SetURL(val string) {
	s.URL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *FeedResponseItem) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *FeedResponseItem) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetUserID sets the value of UserID.
func (s *FeedResponseItem) SetUserID(val uuid.UUID) {
	s.UserID = val
}

func (*FeedResponseItem) feedsPostRes() {}

type FeedsFollowFeedFallowIDDeleteBadRequest ErrorResponse

func (*FeedsFollowFeedFallowIDDeleteBadRequest) feedsFollowFeedFallowIDDeleteRes() {}

type FeedsFollowFeedFallowIDDeleteInternalServerError ErrorResponse

func (*FeedsFollowFeedFallowIDDeleteInternalServerError) feedsFollowFeedFallowIDDeleteRes() {}

// FeedsFollowFeedFallowIDDeleteNoContent is response for FeedsFollowFeedFallowIDDelete operation.
type FeedsFollowFeedFallowIDDeleteNoContent struct{}

func (*FeedsFollowFeedFallowIDDeleteNoContent) feedsFollowFeedFallowIDDeleteRes() {}

type FeedsFollowFeedFallowIDDeleteUnauthorized ErrorResponse

func (*FeedsFollowFeedFallowIDDeleteUnauthorized) feedsFollowFeedFallowIDDeleteRes() {}

type FeedsFollowGetInternalServerError ErrorResponse

func (*FeedsFollowGetInternalServerError) feedsFollowGetRes() {}

type FeedsFollowGetUnauthorized ErrorResponse

func (*FeedsFollowGetUnauthorized) feedsFollowGetRes() {}

type FeedsFollowPostBadRequest ErrorResponse

func (*FeedsFollowPostBadRequest) feedsFollowPostRes() {}

type FeedsFollowPostCreated struct {
	ID        uuid.UUID `json:"id"`
	FeedID    uuid.UUID `json:"feed_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *FeedsFollowPostCreated) GetID() uuid.UUID {
	return s.ID
}

// GetFeedID returns the value of FeedID.
func (s *FeedsFollowPostCreated) GetFeedID() uuid.UUID {
	return s.FeedID
}

// GetUserID returns the value of UserID.
func (s *FeedsFollowPostCreated) GetUserID() uuid.UUID {
	return s.UserID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *FeedsFollowPostCreated) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *FeedsFollowPostCreated) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *FeedsFollowPostCreated) SetID(val uuid.UUID) {
	s.ID = val
}

// SetFeedID sets the value of FeedID.
func (s *FeedsFollowPostCreated) SetFeedID(val uuid.UUID) {
	s.FeedID = val
}

// SetUserID sets the value of UserID.
func (s *FeedsFollowPostCreated) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *FeedsFollowPostCreated) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *FeedsFollowPostCreated) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*FeedsFollowPostCreated) feedsFollowPostRes() {}

type FeedsFollowPostInternalServerError ErrorResponse

func (*FeedsFollowPostInternalServerError) feedsFollowPostRes() {}

type FeedsFollowPostReq struct {
	FeedID string `json:"feed_id"`
}

// GetFeedID returns the value of FeedID.
func (s *FeedsFollowPostReq) GetFeedID() string {
	return s.FeedID
}

// SetFeedID sets the value of FeedID.
func (s *FeedsFollowPostReq) SetFeedID(val string) {
	s.FeedID = val
}

type FeedsFollowPostUnauthorized ErrorResponse

func (*FeedsFollowPostUnauthorized) feedsFollowPostRes() {}

type FeedsGetBadRequest ErrorResponse

func (*FeedsGetBadRequest) feedsGetRes() {}

type FeedsGetInternalServerError ErrorResponse

func (*FeedsGetInternalServerError) feedsGetRes() {}

type FeedsGetUnauthorized ErrorResponse

func (*FeedsGetUnauthorized) feedsGetRes() {}

type FeedsPostBadRequest ErrorResponse

func (*FeedsPostBadRequest) feedsPostRes() {}

type FeedsPostInternalServerError ErrorResponse

func (*FeedsPostInternalServerError) feedsPostRes() {}

type FeedsPostReq struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// GetName returns the value of Name.
func (s *FeedsPostReq) GetName() string {
	return s.Name
}

// GetURL returns the value of URL.
func (s *FeedsPostReq) GetURL() string {
	return s.URL
}

// SetName sets the value of Name.
func (s *FeedsPostReq) SetName(val string) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *FeedsPostReq) SetURL(val string) {
	s.URL = val
}

type FeedsPostUnauthorized ErrorResponse

func (*FeedsPostUnauthorized) feedsPostRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PostResponse
type PostResponse struct {
	Posts []PostResponseItem `json:"posts"`
}

// GetPosts returns the value of Posts.
func (s *PostResponse) GetPosts() []PostResponseItem {
	return s.Posts
}

// SetPosts sets the value of Posts.
func (s *PostResponse) SetPosts(val []PostResponseItem) {
	s.Posts = val
}

func (*PostResponse) postsGetRes() {}

// Ref: #/components/schemas/PostResponseItem
type PostResponseItem struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	URL         string    `json:"url"`
	Content     OptString `json:"content"`
	PublishedAt time.Time `json:"published_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	FeedID      uuid.UUID `json:"feed_id"`
}

// GetID returns the value of ID.
func (s *PostResponseItem) GetID() uuid.UUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *PostResponseItem) GetTitle() string {
	return s.Title
}

// GetURL returns the value of URL.
func (s *PostResponseItem) GetURL() string {
	return s.URL
}

// GetContent returns the value of Content.
func (s *PostResponseItem) GetContent() OptString {
	return s.Content
}

// GetPublishedAt returns the value of PublishedAt.
func (s *PostResponseItem) GetPublishedAt() time.Time {
	return s.PublishedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PostResponseItem) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *PostResponseItem) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetFeedID returns the value of FeedID.
func (s *PostResponseItem) GetFeedID() uuid.UUID {
	return s.FeedID
}

// SetID sets the value of ID.
func (s *PostResponseItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *PostResponseItem) SetTitle(val string) {
	s.Title = val
}

// SetURL sets the value of URL.
func (s *PostResponseItem) SetURL(val string) {
	s.URL = val
}

// SetContent sets the value of Content.
func (s *PostResponseItem) SetContent(val OptString) {
	s.Content = val
}

// SetPublishedAt sets the value of PublishedAt.
func (s *PostResponseItem) SetPublishedAt(val time.Time) {
	s.PublishedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PostResponseItem) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *PostResponseItem) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetFeedID sets the value of FeedID.
func (s *PostResponseItem) SetFeedID(val uuid.UUID) {
	s.FeedID = val
}

type PostsGetBadRequest ErrorResponse

func (*PostsGetBadRequest) postsGetRes() {}

type PostsGetInternalServerError ErrorResponse

func (*PostsGetInternalServerError) postsGetRes() {}

type PostsGetUnauthorized ErrorResponse

func (*PostsGetUnauthorized) postsGetRes() {}

// Ref: #/components/schemas/UserResponse
type UserResponse struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	APIKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *UserResponse) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *UserResponse) GetName() string {
	return s.Name
}

// GetAPIKey returns the value of APIKey.
func (s *UserResponse) GetAPIKey() string {
	return s.APIKey
}

// GetCreatedAt returns the value of CreatedAt.
func (s *UserResponse) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *UserResponse) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *UserResponse) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *UserResponse) SetName(val string) {
	s.Name = val
}

// SetAPIKey sets the value of APIKey.
func (s *UserResponse) SetAPIKey(val string) {
	s.APIKey = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *UserResponse) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *UserResponse) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*UserResponse) usersGetRes()  {}
func (*UserResponse) usersPostRes() {}

type UsersGetNotFound ErrorResponse

func (*UsersGetNotFound) usersGetRes() {}

type UsersGetUnauthorized ErrorResponse

func (*UsersGetUnauthorized) usersGetRes() {}

type UsersPostBadRequest ErrorResponse

func (*UsersPostBadRequest) usersPostRes() {}

type UsersPostInternalServerError ErrorResponse

func (*UsersPostInternalServerError) usersPostRes() {}

type UsersPostReq struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *UsersPostReq) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *UsersPostReq) SetName(val string) {
	s.Name = val
}
