// Code generated by ogen, DO NOT EDIT.
package openapi

type FeedsFollowFeedFallowIDDeleteRes interface {
	feedsFollowFeedFallowIDDeleteRes()
}

type FeedsFollowGetRes interface {
	feedsFollowGetRes()
}

type FeedsFollowPostRes interface {
	feedsFollowPostRes()
}

type FeedsGetRes interface {
	feedsGetRes()
}

type FeedsPostRes interface {
	feedsPostRes()
}

type PostsGetRes interface {
	postsGetRes()
}

type UsersGetRes interface {
	usersGetRes()
}

type UsersPostRes interface {
	usersPostRes()
}
